### ISSUE TITLE
[Question] gladLoadGL error

### ISSUE THREAD

**Issue by augustcat0016** [PKU-MARL/safety-gymnasium#21]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-MARL/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/safety-gymnasium/discussions/new).

### Questions

I encounterred this issue when I use `env.render()` with `render_mode="rgb_array"`.
<img width="501" alt="1546e0bc3290bd0e102dde3c7424452" src="https://user-images.githubusercontent.com/43946314/219277814-a17ec5fe-fdd4-4f27-aa98-e1edaf3eab14.png">

In my bashrc, there is a line related to OpenGL library, `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so:/usr/lib/nvidia-415/libGL.so`, but it still dosen't work.

**Comment by zmsn-2077** [comment]
One solution is add `export MUJOCO_GL=egl` to your `~/.bashrc`, and `source ~/.bashrc`.
Some similar issues you can refer to:
For more details, you can refer to [How to use the vision-based Safety Gymnasium in a headless server](https://github.com/PKU-MARL/omnisafe/issues/27).
