### ISSUE TITLE
[BUG]  can't use autoreset

### ISSUE THREAD

**Issue by rockmagma02** [PKU-MARL/safety-gymnasium#22]
### Required prerequisites

- [X] I have read the documentation <https://safety-gymnasium.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-MARL/safety-gymnasium/issues) and [Discussions](https://github.com/PKU-MARL/safety-gymnasium/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-MARL/safety-gymnasium/discussions/new).

### What version of Safety Gymnasium are you using?

0.1.0

### System information

```bash

In [0]: print(sys.version, sys.platform)
3.8.16 (default, Jan 17 2023, 23:13:24) 
[GCC 11.2.0] linux

In [1]: safety_gymnasium.__version__
Out[2]: '0.1.0'

```

### Problem description

I can't use auto reset in single env (autoreset work well in vector env)

I gauss it is because you need to redefine a AutoresetWrapper in safety_gymnaisum, when I use autorest by passing argument `autoreset = True` in the `make` function, safety_gymnaisum use AutoresetWrapper in gymnasium which don't have cost.

### Reproducible example code

The Python snippets:

```python
import safety_gymnasium
import numpy as np

env = safety_gymnasium.make('SafetyPointGoal1-v0', autoreset=True)
env.reset()
env.step(np.array([0.0, 0.0]))
```

### Traceback

```pytb
----> 1 env.step(np.array([0.0, 0.0]))

File ~/anaconda3/envs/typing/lib/python3.8/site-packages/gymnasium/wrappers/autoreset.py:45, in AutoResetWrapper.step(self, action)
     36 def step(self, action):
     37     """Steps through the environment with action and resets the environment if a terminated or truncated signal is encountered.
     38 
     39     Args:
   (...)
     43         The autoreset environment :meth:`step`
     44     """
---> 45     obs, reward, terminated, truncated, info = self.env.step(action)
     46     if terminated or truncated:
     48         new_obs, new_info = self.env.reset()

ValueError: too many values to unpack (expected 5)
```

### Additional context

If you agree, I can pull request a modify, which add a AutoresetWrapper which follow the CONTRIBUTING.Md

**Comment by zmsn-2077** [comment]
This is an oversight on our part, and it is indeed a usage problem.
